import { ICON_MAP } from "./data/icon-map"

/**
 * Icon class normalization. Icon names are DATA in RedLeaf -- entity `data.icon`
 * fields, plugin manifests, seed files -- so stored strings outlive whatever icon
 * font the app currently ships. Every icon render must pass through here (via
 * the <Icon> component) so legacy FontAwesome strings keep rendering after the
 * Phosphor migration: "fa-solid fa-house" -> "ph-bold ph-house".
 *
 * This lives in @redbamboo/ui rather than the host app because plugin frontends
 * (Nova, ...) render entity-supplied icon strings too, and a plugin that can't
 * reach the normalizer silently emits dead classes.
 *
 * The mapping table is generated by redleaf/scripts/build-icon-map.mjs from
 * scripts/icon-map.overrides.json + the @phosphor-icons/core catalog.
 */

const STYLES: Record<string, string> = ICON_MAP.styles
const UTILITIES: Record<string, string> = ICON_MAP.utilities
const ICONS: Record<string, string> = ICON_MAP.icons

// Phosphor weight classes select the font-family; without one an icon glyph
// class renders nothing.
const WEIGHTS = new Set(["ph", "ph-thin", "ph-light", "ph-bold", "ph-fill", "ph-duotone"])

const cache = new Map<string, string>()

export function normalizeIcon(name: string): string {
  const cached = cache.get(name)
  if (cached !== undefined) return cached

  const out: string[] = []
  for (const token of name.split(/\s+/)) {
    if (!token) continue
    if (token === "fa" || token.startsWith("fa-")) {
      const mapped = STYLES[token] ?? UTILITIES[token] ?? ICONS[token]
      // "" = deliberately dropped (fa-sharp); undefined = unknown fa token,
      // dropped rather than emitting a dead class.
      if (mapped) out.push(mapped)
      continue
    }
    out.push(token)
  }
  if (out.some(t => t.startsWith("ph-") && !WEIGHTS.has(t)) && !out.some(t => WEIGHTS.has(t)))
    out.unshift("ph-bold")

  const result = out.join(" ")
  cache.set(name, result)
  return result
}
