import { useEffect,useMemo,useRef,useState } from "react"
import type { WorkspaceEntity,WorkspaceEntityPage,WorkspaceField,WorkspaceSnapshot,WorkspaceTransport,WorkspaceType } from "./types"
type Props={snapshot:WorkspaceSnapshot;transport:WorkspaceTransport;onRefresh:()=>Promise<void>;readOnly?:boolean;initialEntityId?:string}
type Folder={key:string;title:string;types:WorkspaceType[]}
type PageState=WorkspaceEntityPage&{loading:boolean;error:string}
const pageSize=50
const protectedKeys=new Set(["owner_id","owner_agent_id","owner_plugin","installation","confidential","parent"])
const empty=(v:unknown)=>v==null||v===""||Array.isArray(v)&&!v.length
function object(v:unknown):Record<string,unknown>{if(v&&typeof v==="object"&&!Array.isArray(v))return v as Record<string,unknown>;if(typeof v==="string")try{return JSON.parse(v)}catch{}return{}}
function options(f:WorkspaceField){const value=f.constraints;if(Array.isArray(value))return value.map(String);const parsed=object(value).options;return Array.isArray(parsed)?parsed.map(String):[]}
function Glyph({value}:{value?:string|null}){const name=value?.replace(/^ph-(?:bold|regular) ph-/,"").replaceAll("-"," ")||"record";return <span className="rbw-glyph" aria-hidden="true">{name[0].toUpperCase()}</span>}
function EntityButton({entity,type,selected,choose}:{entity:WorkspaceEntity;type?:WorkspaceType;selected:boolean;choose:(id:string)=>void}){return <button className={selected?"is-selected":""} onClick={()=>choose(entity.id)}><Glyph value={String(entity.data.icon||type?.icon||"")}/><span>{entity.name}</span><small>{type?.name||entity.typeSlug}</small></button>}
export function WorkspaceExplorer({snapshot,transport,onRefresh,readOnly=false,initialEntityId}:Props){
 const initial=snapshot.entities.find(e=>e.id===initialEntityId)||snapshot.root
 const [selected,setSelected]=useState(initial),[query,setQuery]=useState(""),[appliedQuery,setAppliedQuery]=useState(""),[createOpen,setCreateOpen]=useState(false),[mobileDetail,setMobileDetail]=useState(false)
 const [openFolders,setOpenFolders]=useState<Record<string,boolean>>({}),[pages,setPages]=useState<Record<string,PageState>>({})
 const sidebarSlot=useRef<HTMLDivElement>(null),[sidebarHeight,setSidebarHeight]=useState(620)
 const contentTypes=snapshot.types.filter(t=>!t.system&&t.slug!=="page"),systemTypes=snapshot.types.filter(t=>t.system)
 const folders=useMemo(()=>{const result:Folder[]=[];const page=snapshot.types.find(t=>t.slug==="page");if(page)result.push({key:"pages",title:"Pages",types:[page]});const grouped=new Map<string,WorkspaceType[]>();for(const type of contentTypes){const title=type.folder?.trim()||type.name;grouped.set(title,[...(grouped.get(title)||[]),type])}for(const [title,types] of grouped)result.push({key:`folder:${title}`,title,types});if(systemTypes.length)result.push({key:"system",title:"System",types:systemTypes});return result},[snapshot.types])
 const typeFor=(entity:WorkspaceEntity)=>snapshot.types.find(t=>t.slug===entity.typeSlug)
 const stateKey=(folder:Folder,search="")=>`${folder.key}\u0000${search}`
 async function load(folder:Folder,append=false,search=""){
  const key=stateKey(folder,search),current=pages[key];if(current?.loading||append&&!current?.nextCursor)return
  setPages(value=>({...value,[key]:{items:append?current?.items||[]:[],total:current?.total||0,nextCursor:current?.nextCursor,loading:true,error:""}}))
  try{const next=await transport.list({typeSlugs:folder.types.map(t=>t.slug),query:search||undefined,cursor:append?current?.nextCursor:null,limit:pageSize});setPages(value=>({...value,[key]:{...next,items:append?[...(current?.items||[]),...next.items]:next.items,loading:false,error:""}}))}
  catch(cause){setPages(value=>({...value,[key]:{items:current?.items||[],total:current?.total||0,nextCursor:current?.nextCursor,loading:false,error:cause instanceof Error?cause.message:"Records could not be loaded."}}))}
 }
 useEffect(()=>{const timer=window.setTimeout(()=>setAppliedQuery(query.trim()),220);return()=>window.clearTimeout(timer)},[query])
 useEffect(()=>{let frame=0;const update=()=>{const top=sidebarSlot.current?.getBoundingClientRect().top??16;const next=Math.max(280,Math.floor(window.innerHeight-Math.max(16,top)-16));setSidebarHeight(value=>value===next?value:next)},schedule=()=>{window.cancelAnimationFrame(frame);frame=window.requestAnimationFrame(update)},observer=new ResizeObserver(schedule);observer.observe(document.body);schedule();window.addEventListener("resize",schedule);return()=>{observer.disconnect();window.removeEventListener("resize",schedule);window.cancelAnimationFrame(frame)}},[])
 useEffect(()=>{if(appliedQuery){const search:Folder={key:"search",title:"Search results",types:snapshot.types};void load(search,false,appliedQuery)}},[appliedQuery,snapshot.types])
 const choose=(id:string)=>{const entity=Object.values(pages).flatMap(page=>page.items).find(item=>item.id===id)||snapshot.entities.find(item=>item.id===id)||snapshot.root;setSelected(entity);setMobileDetail(true)}
 const replace=(entity:WorkspaceEntity)=>{setSelected(entity);setPages(value=>Object.fromEntries(Object.entries(value).map(([key,page])=>[key,{...page,items:page.items.map(item=>item.id===entity.id?entity:item)}]))) }
 const remove=(entity:WorkspaceEntity)=>{setPages(value=>Object.fromEntries(Object.entries(value).map(([key,page])=>[key,{...page,total:Math.max(0,page.total-(page.items.some(item=>item.id===entity.id)?1:0)),items:page.items.filter(item=>item.id!==entity.id)}])));setSelected(snapshot.root)}
 const loadedEntities=useMemo(()=>{const map=new Map<string,WorkspaceEntity>([[snapshot.root.id,snapshot.root],...snapshot.entities.map(e=>[e.id,e] as const)]);for(const page of Object.values(pages))for(const entity of page.items)map.set(entity.id,entity);map.set(selected.id,selected);return [...map.values()]},[pages,selected,snapshot])
 const renderFolder=(folder:Folder,search="")=>{const key=stateKey(folder,search),state=pages[key],open=search?true:!!openFolders[folder.key];return <section className={`rbw-group${folder.key==="system"?" rbw-system":""}`} key={key}><button className="rbw-group-heading" aria-expanded={open} onClick={()=>{if(search)return;const next=!open;setOpenFolders(value=>({...value,[folder.key]:next}));if(next&&!state)void load(folder)}}><span>{folder.title}</span>{state&&<small>{state.total}</small>}<i>{open?"−":"+"}</i></button>{open&&<div className="rbw-group-body">{state?.error&&<p className="rbw-empty is-error" role="alert">{state.error}</p>}{state?.items.map(entity=><EntityButton key={entity.id} entity={entity} type={typeFor(entity)} selected={selected.id===entity.id} choose={choose}/>)}{state?.loading&&<p className="rbw-empty" role="status">Loading…</p>}{state&&!state.loading&&!state.items.length&&<p className="rbw-empty">{search?"No records match that search.":"No records here."}</p>}{state?.nextCursor&&<button className="rbw-load-more" onClick={()=>void load(folder,true,search)}>Load more <small>{state.items.length} of {state.total}</small></button>}</div>}</section>}
 const searchFolder:Folder={key:"search",title:"Search results",types:snapshot.types}
 return <div className={`rbw-workspace${mobileDetail?" is-detail":""}`} style={{"--rbw-sidebar-height":`${sidebarHeight}px`} as React.CSSProperties}><div className="rbw-sidebar-slot" ref={sidebarSlot}><aside className="rbw-sidebar" aria-label="Workspace contents"><div className="rbw-sidebar-top"><label className="rbw-search"><span aria-hidden="true">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the workspace" aria-label="Search workspace"/></label>{!readOnly&&<button className="rbw-new" onClick={()=>setCreateOpen(true)}><span>＋</span>New</button>}</div><nav className="rbw-tree"><button className={selected.id===snapshot.root.id?"is-selected":""} onClick={()=>{setSelected(snapshot.root);setMobileDetail(true)}}><Glyph value="workspace"/><span>{snapshot.root.name}</span></button>{appliedQuery?renderFolder(searchFolder,appliedQuery):folders.map(folder=>renderFolder(folder))}</nav></aside></div><main className="rbw-detail"><button className="rbw-mobile-back" onClick={()=>setMobileDetail(false)}>← Workspace</button><Editor key={selected.id} entity={selected} type={typeFor(selected)} entities={loadedEntities} transport={transport} readOnly={readOnly||selected.id===snapshot.root.id} onSaved={async entity=>{replace(entity);await onRefresh()}} onDeleted={async()=>{remove(selected);await onRefresh()}}/></main>{createOpen&&<Create root={snapshot.root} pages={loadedEntities.filter(e=>e.typeSlug==="page")} types={contentTypes} transport={transport} close={()=>setCreateOpen(false)} created={async entity=>{setSelected(entity);setMobileDetail(true);setCreateOpen(false);await onRefresh()}}/>}</div>
}
function Editor({entity,type,entities,transport,readOnly,onSaved,onDeleted}:{entity:WorkspaceEntity;type?:WorkspaceType;entities:WorkspaceEntity[];transport:WorkspaceTransport;readOnly:boolean;onSaved:(entity:WorkspaceEntity)=>Promise<void>;onDeleted:()=>Promise<void>}){
 const [name,setName]=useState(entity.name),[data,setData]=useState({...entity.data}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("")
 const fields=(type?.fields||[]).filter(f=>!protectedKeys.has(f.key)).sort((a,b)=>a.sortOrder-b.sortOrder),changed=name!==entity.name||JSON.stringify(data)!==JSON.stringify(entity.data)
 async function save(){if(busy||readOnly||!name.trim())return;setBusy(true);setError("");setNotice("");try{const saved=await transport.save(entity.id,{name:name.trim(),data,expectedUpdatedAt:entity.updatedAt});setNotice("Saved.");await onSaved(saved)}catch(e){setError(e instanceof Error?e.message:"This record could not be saved.")}finally{setBusy(false)}}
 async function remove(){if(busy||readOnly||!confirm(`Delete “${entity.name}”?`))return;setBusy(true);setError("");try{await transport.remove(entity.id,entity.updatedAt);await onDeleted()}catch(e){setError(e instanceof Error?e.message:"This record could not be deleted.");setBusy(false)}}
 return <article className="rbw-document"><header><div className="rbw-document-icon"><Glyph value={String(data.icon||type?.icon||"")}/></div><div><span>{type?.name||entity.typeSlug}</span><input aria-label="Record title" value={name} onChange={e=>setName(e.target.value)} disabled={readOnly}/></div></header>{type?.description&&<p className="rbw-type-description">{type.description}</p>}{error&&<p className="rbw-feedback is-error" role="alert">{error}</p>}{notice&&<p className="rbw-feedback" role="status">{notice}</p>}{!fields.length?<div className="rbw-blank"><strong>No editable fields</strong><p>{readOnly?"Choose a record from the left to inspect and edit it.":"This entity type does not declare any fields."}</p></div>:<div className="rbw-fields">{fields.map(f=><Field key={f.key} field={f} value={data[f.key]} entities={entities} set={v=>setData(d=>({...d,[f.key]:v}))} disabled={readOnly||busy}/>)}</div>}{!readOnly&&<footer><button className="rbw-save" disabled={!changed||busy||!name.trim()||fields.some(f=>f.required&&empty(data[f.key]))} onClick={()=>void save()}>{busy?"Saving…":"Save changes"}</button><span>{changed?"Unsaved changes":"All changes saved"}</span><button className="rbw-delete" disabled={busy} onClick={()=>void remove()}>Delete</button></footer>}</article>
}
function Field({field,value,entities,set,disabled}:{field:WorkspaceField;value:unknown;entities:WorkspaceEntity[];set:(v:unknown)=>void;disabled:boolean}){
 const kind=field.fieldType,target=String(object(field.constraints).target_type||""),candidates=target?entities.filter(e=>e.typeSlug===target):entities,selected=Array.isArray(value)?value.map(String):[];let control:React.ReactNode
 if(kind==="boolean")control=<input type="checkbox" checked={value===true} onChange={e=>set(e.target.checked)} disabled={disabled}/>
 else if(["number","integer","float"].includes(kind))control=<input type="number" step={kind==="float"?"any":"1"} value={value==null?"":String(value)} onChange={e=>set(e.target.value===""?null:Number(e.target.value))} disabled={disabled}/>
 else if(kind==="date"||kind==="datetime")control=<input type={kind==="date"?"date":"datetime-local"} value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}/>
 else if(kind==="select")control=<select value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}><option value="">Select…</option>{options(field).map(o=><option key={o}>{o}</option>)}</select>
 else if(kind==="multi_select")control=<div className="rbw-chips">{options(field).map(o=><label key={o}><input type="checkbox" checked={selected.includes(o)} onChange={()=>set(selected.includes(o)?selected.filter(x=>x!==o):[...selected,o])} disabled={disabled}/>{o}</label>)}</div>
 else if(kind==="entity_ref")control=<select value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}><option value="">None</option>{candidates.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select>
 else if(kind==="entity_list")control=<div className="rbw-reference-list">{candidates.map(e=><label key={e.id}><input type="checkbox" checked={selected.includes(e.id)||selected.includes(e.slug)} onChange={()=>set(selected.includes(e.id)?selected.filter(x=>x!==e.id):[...selected,e.id])} disabled={disabled}/>{e.name}</label>)}</div>
 else if(["markdown","text","json","any"].includes(kind)||String(field.displayHints||"").includes("multiline"))control=<textarea rows={kind==="markdown"?14:5} value={kind==="json"&&typeof value!=="string"?JSON.stringify(value||{},null,2):typeof value==="string"?value:""} onChange={e=>{if(kind==="json")try{set(JSON.parse(e.target.value))}catch{set(e.target.value)}else set(e.target.value)}} disabled={disabled}/>
 else control=<input value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}/>
 return <label className={`rbw-field is-${kind}`}><span>{field.name}{field.required&&<b> *</b>}</span>{field.description&&<small>{field.description}</small>}{control}</label>
}
function Create({root,pages,types,transport,close,created}:{root:WorkspaceEntity;pages:WorkspaceEntity[];types:WorkspaceType[];transport:WorkspaceTransport;close:()=>void;created:(e:WorkspaceEntity)=>Promise<void>}){
 const [typeSlug,setTypeSlug]=useState(types[0]?.slug||""),[name,setName]=useState(""),[parent,setParent]=useState(root.id),[data,setData]=useState<Record<string,unknown>>({}),[busy,setBusy]=useState(false),[error,setError]=useState("");const required=(types.find(t=>t.slug===typeSlug)?.fields||[]).filter(f=>f.required&&!protectedKeys.has(f.key))
 async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim()||!typeSlug||busy||required.some(f=>empty(data[f.key])))return;setBusy(true);setError("");try{await created(await transport.create({typeSlug,name:name.trim(),parent,data}))}catch(c){setError(c instanceof Error?c.message:"The record could not be created.");setBusy(false)}}
 return <div className="rbw-modal" role="dialog" aria-modal="true" aria-labelledby="rbw-create-title" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form onSubmit={submit}><header><h2 id="rbw-create-title">New workspace record</h2><button type="button" aria-label="Close" onClick={close}>×</button></header>{error&&<p className="rbw-feedback is-error" role="alert">{error}</p>}<label>Type<select value={typeSlug} onChange={e=>{setTypeSlug(e.target.value);setData({})}}>{types.map(t=><option value={t.slug} key={t.slug}>{t.folder?`${t.folder} · `:""}{t.name}</option>)}</select></label><label>Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label><label>Location<select value={parent} onChange={e=>setParent(e.target.value)}><option value={root.id}>{root.name}</option>{pages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{required.map(f=><Field key={f.key} field={f} value={data[f.key]} entities={pages} set={v=>setData(d=>({...d,[f.key]:v}))} disabled={busy}/>) }<footer><button type="button" onClick={close}>Cancel</button><button className="rbw-save" disabled={busy||!name.trim()||!typeSlug||required.some(f=>empty(data[f.key]))}>{busy?"Creating…":"Create"}</button></footer></form></div>
}
