import { useEffect,useMemo,useState } from "react"
import type { WorkspaceEntity,WorkspaceField,WorkspaceSnapshot,WorkspaceTransport,WorkspaceType } from "./types"
type Props={snapshot:WorkspaceSnapshot;transport:WorkspaceTransport;onRefresh:()=>Promise<void>;readOnly?:boolean;initialEntityId?:string}
const protectedKeys=new Set(["owner_id","owner_agent_id","owner_plugin","installation","confidential","parent"])
const empty=(v:unknown)=>v==null||v===""||Array.isArray(v)&&!v.length
function object(v:unknown):Record<string,unknown>{if(v&&typeof v==="object"&&!Array.isArray(v))return v as Record<string,unknown>;if(typeof v==="string")try{return JSON.parse(v)}catch{}return{}}
function options(f:WorkspaceField){const value=f.constraints;if(Array.isArray(value))return value.map(String);const parsed=object(value).options;return Array.isArray(parsed)?parsed.map(String):[]}
function Glyph({value}:{value?:string|null}){const name=value?.replace(/^ph-(?:bold|regular) ph-/,"").replaceAll("-"," ")||"record";return <span className="rbw-glyph" aria-hidden="true">{name[0].toUpperCase()}</span>}
function Group({title,count,children}:{title:string;count:number;children:React.ReactNode}){return <section className="rbw-group"><div className="rbw-group-heading"><span>{title}</span><small>{count}</small></div>{children}</section>}
function EntityButton({entity,type,selected,choose}:{entity:WorkspaceEntity;type?:WorkspaceType;selected:boolean;choose:(id:string)=>void}){return <button className={selected?"is-selected":""} onClick={()=>choose(entity.id)}><Glyph value={String(entity.data.icon||type?.icon||"")}/><span>{entity.name}</span><small>{type?.name||entity.typeSlug}</small></button>}
export function WorkspaceExplorer({snapshot,transport,onRefresh,readOnly=false,initialEntityId}:Props){
 const [selectedId,setSelectedId]=useState(initialEntityId||snapshot.root.id),[query,setQuery]=useState(""),[createOpen,setCreateOpen]=useState(false),[systemOpen,setSystemOpen]=useState(false),[mobileDetail,setMobileDetail]=useState(false)
 const selected=selectedId===snapshot.root.id?snapshot.root:snapshot.entities.find(e=>e.id===selectedId)||snapshot.root
 useEffect(()=>{if(selectedId!==snapshot.root.id&&!snapshot.entities.some(e=>e.id===selectedId))setSelectedId(snapshot.root.id)},[snapshot,selectedId])
 const visible=useMemo(()=>{const q=query.trim().toLowerCase();return q?snapshot.entities.filter(e=>e.name.toLowerCase().includes(q)||e.typeSlug.toLowerCase().includes(q)):snapshot.entities},[snapshot.entities,query])
 const contentTypes=snapshot.types.filter(t=>!t.system&&t.slug!=="page"),systemTypes=snapshot.types.filter(t=>t.system),pages=visible.filter(e=>e.typeSlug==="page")
 const choose=(id:string)=>{setSelectedId(id);setMobileDetail(true)},typeFor=(e:WorkspaceEntity)=>snapshot.types.find(t=>t.slug===e.typeSlug)
 return <div className={`rbw-workspace${mobileDetail?" is-detail":""}`}><aside className="rbw-sidebar" aria-label="Workspace contents"><div className="rbw-sidebar-top"><label className="rbw-search"><span aria-hidden="true">⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search the workspace" aria-label="Search workspace"/></label>{!readOnly&&<button className="rbw-new" onClick={()=>setCreateOpen(true)}><span>＋</span>New</button>}</div><nav className="rbw-tree"><button className={selected.id===snapshot.root.id?"is-selected":""} onClick={()=>choose(snapshot.root.id)}><Glyph value="workspace"/><span>{snapshot.root.name}</span></button>{pages.length>0&&<Group title="Pages" count={pages.length}>{pages.map(e=><EntityButton key={e.id} entity={e} type={typeFor(e)} selected={selected.id===e.id} choose={choose}/>)}</Group>}{contentTypes.map(t=>{const rows=visible.filter(e=>e.typeSlug===t.slug);return rows.length?<Group key={t.slug} title={t.folder||t.name} count={rows.length}><div className="rbw-type-label"><Glyph value={t.icon}/>{t.name}</div>{rows.map(e=><EntityButton key={e.id} entity={e} type={t} selected={selected.id===e.id} choose={choose}/>)}</Group>:null})}{systemTypes.length>0&&<section className="rbw-group rbw-system"><button className="rbw-group-heading" aria-expanded={systemOpen} onClick={()=>setSystemOpen(v=>!v)}><span>System</span><small>{visible.filter(e=>systemTypes.some(t=>t.slug===e.typeSlug)).length}</small><i>{systemOpen?"−":"+"}</i></button>{systemOpen&&systemTypes.map(t=>{const rows=visible.filter(e=>e.typeSlug===t.slug);return rows.length?<div key={t.slug}><div className="rbw-type-label"><Glyph value={t.icon}/>{t.name}</div>{rows.map(e=><EntityButton key={e.id} entity={e} type={t} selected={selected.id===e.id} choose={choose}/>)}</div>:null})}</section>}{!visible.length&&<p className="rbw-empty">No records match that search.</p>}</nav></aside><main className="rbw-detail"><button className="rbw-mobile-back" onClick={()=>setMobileDetail(false)}>← Workspace</button><Editor key={selected.id} entity={selected} type={typeFor(selected)} entities={snapshot.entities} transport={transport} readOnly={readOnly||selected.id===snapshot.root.id} onSaved={onRefresh} onDeleted={async()=>{setSelectedId(snapshot.root.id);await onRefresh()}}/></main>{createOpen&&<Create root={snapshot.root} pages={snapshot.entities.filter(e=>e.typeSlug==="page")} types={contentTypes} transport={transport} close={()=>setCreateOpen(false)} created={async e=>{setSelectedId(e.id);setMobileDetail(true);setCreateOpen(false);await onRefresh()}}/>}</div>
}
function Editor({entity,type,entities,transport,readOnly,onSaved,onDeleted}:{entity:WorkspaceEntity;type?:WorkspaceType;entities:WorkspaceEntity[];transport:WorkspaceTransport;readOnly:boolean;onSaved:()=>Promise<void>;onDeleted:()=>Promise<void>}){
 const [name,setName]=useState(entity.name),[data,setData]=useState({...entity.data}),[busy,setBusy]=useState(false),[error,setError]=useState(""),[notice,setNotice]=useState("")
 const fields=(type?.fields||[]).filter(f=>!protectedKeys.has(f.key)).sort((a,b)=>a.sortOrder-b.sortOrder),changed=name!==entity.name||JSON.stringify(data)!==JSON.stringify(entity.data)
 async function save(){if(busy||readOnly||!name.trim())return;setBusy(true);setError("");setNotice("");try{await transport.save(entity.id,{name:name.trim(),data,expectedUpdatedAt:entity.updatedAt});setNotice("Saved.");await onSaved()}catch(e){setError(e instanceof Error?e.message:"This record could not be saved.")}finally{setBusy(false)}}
 async function remove(){if(busy||readOnly||!confirm(`Delete “${entity.name}”?`))return;setBusy(true);setError("");try{await transport.remove(entity.id,entity.updatedAt);await onDeleted()}catch(e){setError(e instanceof Error?e.message:"This record could not be deleted.");setBusy(false)}}
 return <article className="rbw-document"><header><div className="rbw-document-icon"><Glyph value={String(data.icon||type?.icon||"")}/></div><div><span>{type?.name||entity.typeSlug}</span><input aria-label="Record title" value={name} onChange={e=>setName(e.target.value)} disabled={readOnly}/></div></header>{type?.description&&<p className="rbw-type-description">{type.description}</p>}{error&&<p className="rbw-feedback is-error" role="alert">{error}</p>}{notice&&<p className="rbw-feedback" role="status">{notice}</p>}{!fields.length?<div className="rbw-blank"><strong>No editable fields</strong><p>{readOnly?"Choose a record from the left to inspect and edit it.":"This entity type does not declare any fields."}</p></div>:<div className="rbw-fields">{fields.map(f=><Field key={f.key} field={f} value={data[f.key]} entities={entities} set={v=>setData(d=>({...d,[f.key]:v}))} disabled={readOnly||busy}/>)}</div>}{!readOnly&&<footer><button className="rbw-save" disabled={!changed||busy||!name.trim()||fields.some(f=>f.required&&empty(data[f.key]))} onClick={()=>void save()}>{busy?"Saving…":"Save changes"}</button><span>{changed?"Unsaved changes":"All changes saved"}</span><button className="rbw-delete" disabled={busy} onClick={()=>void remove()}>Delete</button></footer>}</article>
}
function Field({field,value,entities,set,disabled}:{field:WorkspaceField;value:unknown;entities:WorkspaceEntity[];set:(v:unknown)=>void;disabled:boolean}){
 const kind=field.fieldType,target=String(object(field.constraints).target_type||""),candidates=target?entities.filter(e=>e.typeSlug===target):entities,selected=Array.isArray(value)?value.map(String):[];let control:React.ReactNode
 if(kind==="boolean")control=<input type="checkbox" checked={value===true} onChange={e=>set(e.target.checked)} disabled={disabled}/>
 else if(["number","integer","float"].includes(kind))control=<input type="number" step={kind==="float"?"any":"1"} value={value==null?"":String(value)} onChange={e=>set(e.target.value===""?null:Number(e.target.value))} disabled={disabled}/>
 else if(kind==="date"||kind==="datetime")control=<input type={kind==="date"?"date":"datetime-local"} value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}/>
 else if(kind==="select")control=<select value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}><option value="">Select…</option>{options(field).map(o=><option key={o}>{o}</option>)}</select>
 else if(kind==="multi_select")control=<div className="rbw-chips">{options(field).map(o=><label key={o}><input type="checkbox" checked={selected.includes(o)} onChange={()=>set(selected.includes(o)?selected.filter(x=>x!==o):[...selected,o])} disabled={disabled}/>{o}</label>)}</div>
 else if(kind==="entity_ref")control=<select value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}><option value="">None</option>{candidates.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select>
 else if(kind==="entity_list")control=<div className="rbw-reference-list">{candidates.map(e=><label key={e.id}><input type="checkbox" checked={selected.includes(e.id)||selected.includes(e.slug)} onChange={()=>set(selected.includes(e.id)?selected.filter(x=>x!==e.id):[...selected,e.id])} disabled={disabled}/>{e.name}</label>)}</div>
 else if(["markdown","text","json","any"].includes(kind)||String(field.displayHints||"").includes("multiline"))control=<textarea rows={kind==="markdown"?14:5} value={kind==="json"&&typeof value!=="string"?JSON.stringify(value||{},null,2):typeof value==="string"?value:""} onChange={e=>{if(kind==="json")try{set(JSON.parse(e.target.value))}catch{set(e.target.value)}else set(e.target.value)}} disabled={disabled}/>
 else control=<input value={typeof value==="string"?value:""} onChange={e=>set(e.target.value)} disabled={disabled}/>
 return <label className={`rbw-field is-${kind}`}><span>{field.name}{field.required&&<b> *</b>}</span>{field.description&&<small>{field.description}</small>}{control}</label>
}
function Create({root,pages,types,transport,close,created}:{root:WorkspaceEntity;pages:WorkspaceEntity[];types:WorkspaceType[];transport:WorkspaceTransport;close:()=>void;created:(e:WorkspaceEntity)=>Promise<void>}){
 const [typeSlug,setTypeSlug]=useState(types[0]?.slug||""),[name,setName]=useState(""),[parent,setParent]=useState(root.id),[data,setData]=useState<Record<string,unknown>>({}),[busy,setBusy]=useState(false),[error,setError]=useState("");const required=(types.find(t=>t.slug===typeSlug)?.fields||[]).filter(f=>f.required&&!protectedKeys.has(f.key))
 async function submit(e:React.FormEvent){e.preventDefault();if(!name.trim()||!typeSlug||busy||required.some(f=>empty(data[f.key])))return;setBusy(true);setError("");try{await created(await transport.create({typeSlug,name:name.trim(),parent,data}))}catch(c){setError(c instanceof Error?c.message:"The record could not be created.");setBusy(false)}}
 return <div className="rbw-modal" role="dialog" aria-modal="true" aria-labelledby="rbw-create-title" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><form onSubmit={submit}><header><h2 id="rbw-create-title">New workspace record</h2><button type="button" aria-label="Close" onClick={close}>×</button></header>{error&&<p className="rbw-feedback is-error" role="alert">{error}</p>}<label>Type<select value={typeSlug} onChange={e=>{setTypeSlug(e.target.value);setData({})}}>{types.map(t=><option value={t.slug} key={t.slug}>{t.folder?`${t.folder} · `:""}{t.name}</option>)}</select></label><label>Name<input autoFocus required value={name} onChange={e=>setName(e.target.value)}/></label><label>Location<select value={parent} onChange={e=>setParent(e.target.value)}><option value={root.id}>{root.name}</option>{pages.map(p=><option value={p.id} key={p.id}>{p.name}</option>)}</select></label>{required.map(f=><Field key={f.key} field={f} value={data[f.key]} entities={pages} set={v=>setData(d=>({...d,[f.key]:v}))} disabled={busy}/>) }<footer><button type="button" onClick={close}>Cancel</button><button className="rbw-save" disabled={busy||!name.trim()||!typeSlug||required.some(f=>empty(data[f.key]))}>{busy?"Creating…":"Create"}</button></footer></form></div>
}
